version: '3.8'

services:
  chat-ncp-proxy:
    build: .
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
      - ADMIN_KEY=your-super-secret-admin-key
      - A4F_API_KEY=your-upstream-api-key
      - A4F_BASE_URL=https://your-upstream-api-base-url
    volumes:
      - ./logs:/usr/src/app/logs
      - ./.env:/usr/src/app/.env
    restart: unless-stopped
    networks:
      - proxy-network

  # Optional: nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - chat-ncp-proxy
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge